security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ABCD
      clientSecret: ABCD
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      token-name: access_token
    resource:
      userInfoUri: http://localhost:8081/userinfo
      